### ISSUE TITLE
Error reading Production Tree

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/integration-data-copy#11]
When attempting to copy data from production to integration, it fails attempting to make a call to:

https://familysearch.org/platform/tree/persons/undefined?person=REQUESTED_ID&access_token=YOUR_ACCESS_TOKEN

**Comment by dovy** [comment]
Also broke person search for third parties. Yay.

**Comment by justincy** [comment]
I'm pretty sure this is an issue with the JS SDK URL template parsing, though I have no idea why it just recently stopped working. The URL templates returned by the collections endpoint appear to be the same format.

**Comment by justincy** [comment]
The issue is caused by the `person-with-relationships` template changing from `"https://familysearch.org/platform/tree/persons-with-relationships{?persons,person,access_token}"` to `"https://familysearch.org/platform/tree/persons/{pid}{?access_token,relatives,sourceDescriptions}"`.

**Comment by dovy** [comment]
I figured that was the issue. Changing key value as well as URL reference.  ;)

**Comment by stoicflame** [comment]
Not a changing key value, just the URL.

**Comment by justincy** [comment]
@stoicflame I think he means that `person` changed to `pid`

**Comment by stoicflame** [comment]
Fair enough.

We'll roll back the change and put it behind the `consolidate-redundant-resources` pending mod.

**Comment by dovy** [comment]
Either way, I bypassed this for RecordSeek. Thanks.

**Comment by dovy** [comment]
When person id stopped working as a search form. Previously just the string would function without dashes. That functionality was deprecated causing developers to synthetically insert dashes. I'm sure you recall that now. ;)

Dovy Paukstys
801.706.4076

**Comment by justincy** [comment]
I'll future proof this when v4.1.0 of [fs-traversal](http://www.jsdelivr.com/projects/fs-traversal) is published on the CDN.

**Comment by stoicflame** [comment]
> When person id stopped working as a search form. Previously just the string would function without dashes. That functionality was deprecated causing developers to synthetically insert dashes. I'm sure you recall that now. ;)

Okay. Because the message on FSDN made it sound like there was a previous change to the link template value that broke you before, so I was confused. But you were just talking about a disruption in a different aspect of the system that happened to break the same feature. That makes sense.

**Comment by dovy** [comment]
You are correct. I hope we can eventually move to an API versioning system so I don't have to go back and fix code that has been working for months.

Have you thought about doing a version in the header so users could use the "latest" version, or the version of the API that previously was working for their product? Just an idea I've seen done before. Models like this ensure a truly stable API.

**Comment by stoicflame** [comment]
Yeah, so [last time that came up](https://groups.google.com/a/ldsmail.net/d/msg/fsdn/HTzYM67qT1Q/hla-JebYAwAJ), I made [the assertion that we already have a stable versioning system](https://groups.google.com/a/ldsmail.net/d/msg/fsdn/HTzYM67qT1Q/eOGvZ2WnBAAJ) to ensure a truly stable API and I never heard back from you, so I assumed we were good.

Bad assumption?

So maybe I'll ask the question again: how is the current mechanism insufficient?

**Comment by dovy** [comment]
@stoicflame I can tell you are taking what I am saying from a negative position, so let me explain more thoughtfully.

I am in no way criticizing your development cycles or your planned schedules. Those are quite well laid out, but what I might suggest is a more divergent solution for your API.

One of the best APIs I ever used allowed for sharding of the API. Not so much using the same code base, but even pushing different versions of the same code to major versions. So as they were developing it was "preview" their first version was v1 and the second was v2. Every version used it's own code base so regardless of the regression tests on the new code, the new version of the API did not affect the previous.

The endpoint in question has had 2 major "breaking" changes to it. Not because of an architectural service being removed from your side, but a feature or alteration of how things work.

I think, that if you wanted to be a partner people really enjoyed working with, you'd want to make sure that your new code never broke old code. Regression testing can only go so far, so I suggest a versioning system which would be completely different codebases for the API, frozen at the major release.

I run a framework used by millions of sites on the net. It has been around for 4 years now. You can STILL use the exact same code from when it was first created without anything breaking. If I break something I very quickly release a shim to fix it. My methodology is "new features can't break old functionality."

Yet what I hear from FamilySearch every now and then is "oh, well that's deprecated anyways." I feel that if you shifted to ensure that your "features" don't break your "functional" API endpoints, your third parties would be happier.

I'm hardly involved nowadays, I am too busy helping the companies in New York migrate their big data systems. I am also trying not to be a jerk here. I just believe more people would work with FamilySearch if you were a bit more cautious and less defensive when a problem from your side was pointed out. You're the provider. FS should be the best provider in the world and the best to work with.

At least that's my thought process given who we are and what we stand for. Unfortunately, I have not found that always to be the case, and I am even LDS. 

I do appreciate what you do Ryan. I am not criticizing you, but I am venting my frustrations of what I wish FamilySearch would be. At least, if I was one of your team, that's what I would be championing every day. We have a mission, and we should ensure that everyone wants to work with us.

Just my thoughts. I hope you and your family are well.  :)

**Comment by stoicflame** [comment]
Thanks for taking the time to write up your thoughts. I apologize if my questions are coming across as defensive; I'm hearing some feedback here and I'm trying to turn that feedback into actionable items for my team. I don't question your sincerity or your good intentions, I'm just genuinely trying to identify what we can actually _do_ here to improve.

> One of the best APIs I ever used allowed for sharding of the API. Not so much using the same code base, but even pushing different versions of the same code to major versions. So as they were developing it was "preview" their first version was v1 and the second was v2. Every version used it's own code base so regardless of the regression tests on the new code, the new version of the API did not affect the previous.

Cool.

I genuinely believe that's what we've implemented with the [Pending Modifications](https://familysearch.org/developers/docs/guides/evolution#pending-mods) mechanism. If I'm incorrect, I really want to know what versioning features are missing so we can implement them. Can you tell me what features are missing?

> The endpoint in question has had 2 major "breaking" changes to it. Not because of an architectural service being removed from your side, but a feature or alteration of how things work.

I just want to make sure we're on the same page. We're talking about two distinct disruptions (a.k.a. "breaking changes"), each at a different endpoint. 

The `Person` endpoint was responsible for the first breakage. I think you're saying we should have fixed it instead of making clients adapt. I agree, we should have done that. We didn't respond quickly enough and by the time we realized what needed to be done, all the effected clients had already adapted. Shame on us.

The `Family Tree Collection` endpoint was responsible for the second breakage. You're saying we should have fixed it instead of making clients adapt. I agree, and we did that this time.

Did I misunderstand anything?

> Yet what I hear from FamilySearch every now and then is "oh, well that's deprecated anyways."

I agree that we shouldn't give that impression. Can you think of any other times that we did that other than the dashes-in-person-ids breakage? If so, I'd like to hear about it so we can address it. My impression is that we fixed that problem via better management of our API versioning process using the Pending Modifications mechanism mentioned above and enhancing our communications process. If that impression is incorrect, I really want to know because I can't figure out any additional actionable items to take away here.

It's true that this is a case where something slipped, but we took corrective action as soon as we could. The only thing I can see that we could have done better was to _not_ put the breakage in there in the first place, but I'm afraid I just can't promise that we humans won't ever make a mistake again. The best I can figure out to promise is to take immediate corrective action... like we did here.

> I just believe more people would work with FamilySearch if you were a bit more cautious and less defensive when a problem from your side was pointed out. You're the provider. FS should be the best provider in the world and the best to work with.

I agree.

Again, I'm just struggling to see what actions we need to take here to move us closer to that dream. And again, I'm not trying to be defensive; I'm genuinely trying to figure out the corrective action that needs to be taken.

Thoughts?

**Comment by dovy** [comment]
> I genuinely believe that's what we've implemented with the Pending Modifications mechanism. If I'm incorrect, I really want to know what versioning features are missing so we can implement them. > Can you tell me what features are missing?

Most of the time the FS API works great (except on Sundays when it gets overloaded, ha). Your pending modifications is great for helping people to adapt with new changes and features and the structure for this delivery is great! I am SO glad you've made these changes.

I am suggesting another method that would be more of a drastic alteration on your end, but would add extreme stability to third parties with not a ton of pain on yours.

> I just want to make sure we're on the same page. We're talking about two distinct disruptions (a.k.a. "breaking changes"), each at a different endpoint.

From my perspective both times it was due to the person ID search via getpersonwithrelationships. As you pointed out, both changes came from a parent method and I can truly appreciate that. I didn't realize you had put a fix in for this version, I simply updated to the new endpoint because that's the impression I was getting. Both times I had to put time in updating libraries to get my free product to work. You can imagine how frustrating this would be for people who are on the outside. When an API works one way a few months ago and then suddenly breaks. I KNOW you try to avoid this. I'm not saying I don't see the effort. I just wish there were a way to "lock in the code base" of the version of the API.

That's what I am suggesting. I am suggesting that you put a router in front of your API that would allow users to use the "codebase" that matches the version of your API. You could mirror those versions with your release schedule.

If I want the code from 20160105 (fake release day), and I hardcode that into my headers for the API, you would potentially only serve up that API from that code base.

If I wanted the most recent API, I'd specify nothing, and get the most current, stable code.

If I wanted beta code I'd specify preview and get the preview code.

See it's more than regression testing, we can't always control everything and there are SO many interlocking pieces in the FS API. I'm merely making a suggestion of how to ensure absolute stability from yesterday.

I don't do my side of the work, honestly. I don't test your beta environment. Because my product is simply there to help others. But when something that worked yesterday breaks and I get 20 emails in my inbox in an hour (1000 people using the product every day), it frustrates me. I guess the fact that it was a seeming repeat of the previous issue is what set me off. If I offended, I am sorry. It's not my intent to offend. 

One other thing that might help is an alert mechanism if the API is down. Like a cloudflare type thing that will send an API response of the site down. Or even a status page, somewhere I can point my users to. Suddenly (mostly on Sundays) things will just stop working. I'd love to have somewhere to send people.

I also appreciate you recognizing how one might feel as I. I appreciate your candor and honesty.

**Comment by stoicflame** [comment]
Great. I think we're at least on the same page. I didn't understand what you said about "both changes [coming] from a parent method", but it's probably not really relevant.

We could use the pending modifications mechanism to implement exactly what you describe: the version of the API that was running on January 5, 2016 could stay static in perpetuity and we release all new features under a new "version" defined by a pending mod.

I think the only thing we disagree on is the cost of maintaining older versions. You seem to be implying that it doesn't cost much to maintain an old version. Certainly some versions are easier to maintain than others, but as time moves on and changes aggregate, the cost and complexity of maintaining those older versions continues to build. 

I have no doubt that at some point in your career you've come across a project that is old and really needs to be rewritten and re-architected, but nobody wants to take the time and spend the money to redo it, so they just do what it takes to "make it work" and pile on the technical debt. Ick. Wouldn't you agree that we want the API to be a living, well-maintained, and active project? Nobody wants the API to be bogged down in perpetuity with old, ugly, stale features-- at some point old versions need to be cut off, right?

Assuming we're agreed on that, now it's just a matter of deciding how long old versions live. I have a hard time imagining that you're saying they need to live forever, but I really don't think that anything less meets your explicit goal of "absolute stabililty" and your implicit goal of eliminating frustration for people "on the outside." I would assert that no matter _how_ long we let old, stale code live someone will always be frustrated when it gets cut off.

So I guess I'm just not able to connect the dots between your versioning philosophy, "absolute stability," and the elimination of frustration for people "on the outside." Can you enlighten me?
