### ISSUE TITLE
Getting a 400 Error when clicking "Copy"

### ISSUE THREAD

**Issue by mexin** [FamilySearch/integration-data-copy#12]
This was using http://familysearch.github.io/integration-data-copy/

Tried copying production data to our integration account but as soon as I click the Copy button I get a 400 error in my chrome console, I signed correctly both for production and integration but cannot copy anything.

Thanks for the help!

**Comment by misbach** [comment]
I see that some people get copied over just fine, and some don't. @justincy Do you know why we are getting some 400 errors?

**Comment by justincy** [comment]
I can't duplicate the problem. I'll need someone to give me an example PID that consistently fails, or if the problem is inconsistent just tell me what settings you chose for copying. I tried copying 50 people two different times and never triggered a 400.

**Comment by misbach** [comment]
Try this PID, it seems to be consistent for me. KWCJ-RN4

**Comment by justincy** [comment]
This issue is that the API's returning data which it won't then accept as valid. In the case of https://www.familysearch.org/tree/person/details/KWJ4-C4J they have a Occupation fact with the place listed as "Farmer" instead of the value; that's invalid because the API expects Occupation to have a value instead of a place.

KWJ4-C4X has a similar issue.

I don't think we can solve this one. I don't want to add that level of validation on our end. The best solution is to just fix the bad data in the tree.

**Comment by justincy** [comment]
@mexin BTW if you want help diagnosing what's causing your particularly problem, just send me the person ID you start with.

**Comment by misbach** [comment]
Thanks @justincy !

**Comment by mexin** [comment]
Thanks for explaining @justincy, here you go, this is the PID Im trying to copy L6X4-DVH, I selected "Cousins" and "100" for how many people to copy.

**Comment by justincy** [comment]
@mexin I don't have access to L6X4-DVH in prod; they're likely a living person. Can you run it and tell me the production IDs of the person rows that turn red in the results tables?
