### ISSUE TITLE
Sign In button does nothing when loading index.html from file system

### ISSUE THREAD

**Issue by MrIonic** [FamilySearch/integration-data-copy#9]
Tried:
Firefox 51.0.1 32-bit
Chrome 56.0 64-bit
Internet Explore 11.576 64-bit

I'm getting the impression that this tool was not meant to be run from the file system.  May I suggest adding more detailed instructions to the README.md so people know how to start the tool.  
Thanks!

**Comment by justincy** [comment]
The app can be run locally but the README doesn't attempt to explain how because it's already running at http://familysearch.github.io/integration-data-copy so we figured nobody would try to run it themselves. I'll explain in [your other issue](https://github.com/FamilySearch/integration-data-copy/issues/10) how to configure it locally.

**Comment by MrIonic** [comment]
Justin,
thanks for the fast answer! I'll try the already running instance you suggested and I have a feeling that will work great for my purposes.
Regards
Adam
